### ISSUE TITLE
Fails to work with uploading large files

### ISSUE THREAD

**Issue by chris-day** [LUMII-Syslab/OBIS-SchemaExtractor#3]
Using files larger than 2MB for upload fails. 

The workaround is to rebuild with a builkd/application.properties containing entries for max-file-size and max-request-size.

Example below

```
spring.http.multipart.max-file-size=10GB
spring.http.multipart.max-request-size=10GB
```

**Comment by karlisc** [comment]
Hi!
Thanks for reaching out! Which command/interface are you using to observe this behavior? We usually use http://localhost:8080/swagger-ui.html#/Services%20V2/buildFullSchemaFromEndpointV2UsingPOST, and this normally does not require uploading of files (one can upload, e.g., a class list, or a property list, but that is not going to be very large).
Kārlis

**Comment by chris-day** [comment]
Hi Kārlis - 

It was the RDF/OWL endpoint. I've attached a zip of the owl file in question (still playing with ISO 20022 !)
[iso20022.zip](https://github.com/user-attachments/files/17317703/iso20022.zip)

The command was

`curl -X POST "http://starlord:1234/schema-extractor-rest/v1/owlFile/buildFullSchema?endpointUrl=http%3A%2F%2Fstarlord%3A8080%2Fsparql&abstractPropertyThreshold=10&propertyInstanceCountThreshold=1000&calculateCardinalities=false" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file=@iso20022.rdfxml;type=text/xml"`

**Comment by karlisc** [comment]
Hi Chris!
Currently we are not working actively in retrieving the schemas directly from the .owl files, as well as the schema format that can be obtained, if we load, e.g., smaller .owl files, is not the one that can be used with the recent versions of our tools.
There is one suggestion, however, that might allow you getting some visual interface over your ontology file (accessing its contents, not editing, though). 
I have created a demo for a visual query environment over your ontology in our ViziQuer playground https://viziquer.app
You can go there, create a user (enter any email like string), then log in and create a project according to iso20022 schema (the last in a long list at the moment); this would allow you to create a query diagram and do visual queries over your ontology.
Right now, it should be quite easy also to create such an environment for you on your premises (this includes loading the ontology in a triple store (I used Virtuoso, but it should not matter much, which one), extracting the v2 schema from it and loading it into a current ViziQuer tool).
I include a screenshot of some query examples in an environment. 
![image](https://github.com/user-attachments/assets/fd845e43-0ade-4cf0-aa8f-d29263028d69)
I would be happy to explain the details to you (may be in a short video call -?).
If you would not mind, we could move over to discussing things over email (mine still is karlis.cerans@lumii.lv).

**Comment by chris-day** [comment]
Hi Kārlis - I'll take this offline with you. (What you've done looks great !)

Cheers

Chris
